baseurl = ""
languageCode = "en-us"
title = "Relaxed IK"
theme = "onedly"

#
# Personalization params
#
[params]
    # project specific params
    description = "An inverse kinematics (IK) solver"
    author_url = "http://pages.cs.wisc.edu/~rakita/"
    author_name = "Daniel Rakita"
    project_url = "https://github.com/uwgraphics/relaxed_ik_core"

    # optionally specify where the content is
    # mainSections = ["post"] 

    # social share links to appear at the end
    socialShare          = false
    # Sets specific share to appear on posts (default behavior is to appear)
    socialShareTwitter   = false
    socialShareGoogleplus = false
    socialShareFacebook  = false
    socialShareReddit    = false
    socialShareLinkedin  = false
    socialShareStumbleupon = false
    socialSharePinterest = false
    socialShareEmail = false

    # theme's color scheme
    first_color="white"
    first_border_color="#e7e7e7"
    first_text_color="#333"

    second_color="white"
    second_text_color="#333"

    header_color="#f8f8f8"
    header_text_color="rgb(51, 51, 51)"

    header_link_color="#777"
    header_link_hover_color="rgb(51, 51, 51)"

#
# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. Icons appear at the top of the page.
#
[social]
    # Coding Communities
    github           = "uwgraphics/relaxed_ik_core"
    gitlab           = ""
    stackoverflow    = "" # User Number
    bitbucket        = ""
    jsfiddle         = ""
    codepen          = ""
    # Visual Art Communities
    deviantart       = ""
    flickr           = ""
    behance          = ""
    dribbble         = ""
    # Publishing Communities
    wordpress        = ""
    medium           = ""
    # Professional/Business Oriented Communities
    linkedin         = ""
    linkedin_company = ""
    foursquare       = ""
    xing             = ""
    slideshare       = ""
    # Social Networks
    facebook         = ""
    googleplus       = ""
    reddit           = ""
    quora            = ""
    youtube          = "watch?v=AhsQFJzB8WQ&feature=youtu.be"
    vimeo            = ""
    whatsapp         = "" # WhatsApp Number
    # WeChat and QQ need testing.
    wechat         = ""
    qq             = "" # User ID Number
    instagram        = ""
    tumblr           = ""
    twitter          = ""
    skype            = ""
    snapchat         = ""
    pinterest        = ""
    telegram         = ""
    vine             = ""
    googlescholar    = ""
    orcid            = ""
    researchgate     = ""
    # Email
    email = "rakita@cs.wisc.edu"

#
# Adjust privacy settings
# See: https://gohugo.io/about/hugo-and-gdpr/
#
[privacy]
    [privacy.disqus]
      disable = true

    [privacy.googleAnalytics]
      disable = true
      anonymizeIP = true
      respectDoNotTrack = true
      useSessionStorage = true

    [privacy.instagram]
      disable = true
      simple = true

    [privacy.twitter]
      disable = true
      enableDNT = true
      simple = true

    [privacy.vimeo]
      disable = true
      simple = true

    [privacy.youtube]
      disable = true
      privacyEnhanced = true

#
# In simple mode for Instagram and a site styled with Bootstrap 4, 
# you may want to disable the inlines styles provided by Hugo:
# See: https://gohugo.io/about/hugo-and-gdpr/
#
[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[markup]
  defaultMarkdownHandler = "blackfriday"
