urdf: sawyer.urdf
link_radius: 0.05 
base_links:
  - base_link
ee_links:
  - right_hand
starting_config: [ 0.0, 0.0, -1.5708, 1.5708, 0.0, -1.5708, 0.0 ]
joint_ordering: [ "right_j0", "right_j1", "right_j2", "right_j3", "right_j4", "right_j5", "right_j6" ]
obstacles: