# Enter the information of the robot you want to run RelaxedIK on
loaded_robot:
  name: sawyer_info.yaml # please enter the name of the corresponding info file
  link_radius: 0.05 # by default
  # please select from noECA, ECA, ECA3, and ECAA
  # noECA: doesn't incorporate environment collision avoidance
  # ECA (by default): incorporates environment collision avoidance 
  # ECA3: incorporates environment collision avoidance, but only considers end-effector position goal matching, 
  #       and does not try to match the orientation of goals
  # ECAA: incorporates environment collision avoidance, adaptively adjusts the weight on the orientation 
  #       matching objectives on-the-fly, such that the importance of orientationmatching is reduced 
  #       when the robot is close to a collision state and raised to its standard value  
  #       when the robot is not close to a collision.
  objective_mode: ECA 
  # please type keyboard here if interactive control is desired; if you want to have
  # the robot arm follow a cartesian path, put the animation file in the 
  # animation_files folder and type the file name here
  input_device: keyboard

# scale: usually a list of three float numbers, while a single float number is sufficient for spheres
# animation: there are three options available: static, interactive and [the name of an animation file]. 
#            The option "interactive" means that you will be able to drag the obstacle around with your mouse. 
#            If you want to drive the robot with an animation file, please make sure to put the corresponding 
#            animation file in the animation_files folder
obstacles:
  cuboids:
    - name: box1
      scale: [0.35,0.6,0.002]
      translation: [0.6,0.0,0.0]
      rotation: [0.0,0.0,0.0]
      animation: static
  spheres:
    - name: sphere1
      scale: 0.1
      translation: [0.4,0.4,0.3]
      animation: rotations_sphere1
    - name: sphere2
      scale: 0.15
      translation: [0.5,-0.7,0.3]
      animation: rotations_sphere2
    - name: sphere3
      scale: 0.12
      translation: [0.85,0.15,0.3]
      animation: rotations_sphere3
    - name: sphere4
      scale: 0.06
      translation: [0.6,-0.1,0.9]
      animation: static
  point_cloud:
    - name: bunny
      scale: [2.0,2.0,2.0]
      translation: [1.0,-0.25,0.15]
      rotation: [1.57,0.0,-1.57]
      animation: interactive
      file: bunny
